# Generated by Django 5.2.13 on 2026-04-15 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=10)),
                ('gender_probability', models.FloatField(default=0)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('age_group', models.CharField(max_length=10)),
                ('country_id', models.CharField(max_length=4)),
                ('country_probability', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
