# Generated by Django 5.2.13 on 2026-04-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_managers_profile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=10),
        ),
    ]
