# Generated by Django 5.2.13 on 2026-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sample_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
